apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: java-rest-service-db
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"java-rest-service","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"java-rest-service","namespace":"dev"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"11"}]},"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"api_descriptor","value":{"description":"This is a demo","location":{"path":"/api-docs"},"owner":"Demo Owner","system":"Demo","type":"openapi"}}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"sql.tanzu.vmware.com/v1","kind":"Postgres","name":"customer-profile-database"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/chiarasalvatore/java-rest-service-demo.git"}}}}
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: java-rest-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: java-rest-service
spec:
  name: db
  service:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: customer-profile-database
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: java-rest-service

