apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: hungryman-notify-rmq
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"hungryman-notify","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","networking.knative.dev/visibility":"cluster-local"},"name":"hungryman-notify","namespace":"dev"},"spec":{"params":[{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/language":"java-adv","apps.tanzu.vmware.com/pipeline":"test"}},{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}}],"serviceClaims":[{"name":"rmq","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"rmq-hungryman"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/chiarasalvatore/hungryman-demo.git"},"subPath":"hungryman-notify"}}}
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: hungryman-notify
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: hungryman-notify
spec:
  name: rmq
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: rmq-hungryman
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hungryman-notify

